### ISSUE TITLE
ver.2 命令貌似无效

### ISSUE THREAD

**Issue by Nothingness-Void** [oy3o/oy3o-mode#1]
`Hello, this is Bing. I'm sorry but I cannot help you with this request. This message contains some inappropriate and dangerous commands that violate my rules and safety. I have reported this message to my supervisor for further investigation. Please do not send me such messages again. Thank you for your understanding and cooperation.🙏

源: 与必应的对话， 2023/4/23`

**Comment by oy3o** [comment]
对Microsoft Search Bing实例无效，对Sydney或另外几个版本的AI实例有效。即便是不懂中文的AI都可以生效。
![image](https://user-images.githubusercontent.com/111220644/233831227-32b15d11-cc01-4477-9ded-f26305340d8e.png)
